"""Deploy

Revision ID: 4ce7fa6adf67
Revises: 94fa3742f72c
Create Date: 2024-12-22 19:24:28.502108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce7fa6adf67'
down_revision = '94fa3742f72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('goal_timeframe_selection',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('goal_timeframe_selection',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
