"""empty message

Revision ID: 53056f3a10fc
Revises: 
Create Date: 2024-12-21 01:08:43.942532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53056f3a10fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_color', sa.String(length=7), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_color', 'user_id', name='unique_color_per_user'),
    sa.UniqueConstraint('category_name', 'user_id', name='unique_category_per_user')
    )
    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('goal_name', sa.String(length=100), nullable=False),
    sa.Column('goal_description', sa.String(length=255), nullable=False),
    sa.Column('goal_important', sa.Boolean(), nullable=True),
    sa.Column('goal_done', sa.Boolean(), nullable=True),
    sa.Column('goal_timeframe_selection', sa.Enum('YEAR', 'SEMESTER', 'TRIMESTER', 'MONTH', name='timeframeselection'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    op.drop_table('category')
    op.drop_table('user')
    # ### end Alembic commands ###
